import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-screen overflow-hidden *:mx-auto h-screen flex flex-col justify-between text-5xl">
        <div></div>
      {children}
        <div className="text-xl mb-1 text-gray-700"><Link href="">Github </Link>⬤ (Heavily) Inspired by <Link href="https://x.com/t3dotgg">@t3dotgg</Link>&nbsp;&nbsp;⬤ <Link href="https://x.com/smrdotgg">By @smrdotgg</Link> </div>
      </body>
    </html>
  );
}
